apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: my-angular-app
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
